package in.wynk.payment.core.constant;

import in.wynk.logging.BaseLoggingMarkers;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

public interface PaymentLoggingMarker extends BaseLoggingMarkers {

    Marker APB_ERROR = MarkerFactory.getMarker("APB_ERROR");
    Marker APS_PRE_DEBIT_NOTIFICATION_SUCCESS = MarkerFactory.getMarker("APS_PRE_DEBIT_NOTIFICATION_SUCCESS");
    Marker APS_PRE_DEBIT_NOTIFICATION_ERROR = MarkerFactory.getMarker("APS_PRE_DEBIT_NOTIFICATION_ERROR");
    Marker APS_RENEWAL_STATUS_ERROR = MarkerFactory.getMarker("APS_RENEWAL_STATUS_ERROR");
    Marker APS_RENEWAL_TIMEOUT_ERROR = MarkerFactory.getMarker("APS_RENEWAL_TIMEOUT_ERROR");
    Marker APS_API_FAILURE = MarkerFactory.getMarker("APS_API_FAILURE");
    Marker APS_OPERATION_FAILURE = MarkerFactory.getMarker("APS_OPERATION_FAILURE");
    Marker APS_CHARGING_STATUS_VERIFICATION = MarkerFactory.getMarker("APS_CHARGING_STATUS_VERIFICATION");
    Marker APS_VPA_VERIFICATION = MarkerFactory.getMarker("APS_VPA_VERIFICATION");
    Marker APS_BIN_VERIFICATION = MarkerFactory.getMarker("APS_VPA_VERIFICATION");
    Marker APS_REFUND_STATUS = MarkerFactory.getMarker("APS_REFUND_STATUS");
    Marker APS_CHARGING_FAILURE = MarkerFactory.getMarker("APS_CHARGING_FAILURE");
    Marker APS_VALIDATION_FAILURE = MarkerFactory.getMarker("APS_VALIDATION_FAILURE");

    Marker HTTP_ERROR = MarkerFactory.getMarker("HTTP_ERROR");
    Marker PAYTM_ERROR = MarkerFactory.getMarker("PAYTM_ERROR");

    Marker PAYU_TDR_ERROR= MarkerFactory.getMarker("PAYU_TDR_ERROR");
    Marker SUBSCRIPTION_ERROR = MarkerFactory.getMarker("SUBSCRIPTION_ERROR");
    Marker RENEWAL_ELIGIBILITY_API_ERROR = MarkerFactory.getMarker("RENEWAL_ELIGIBILITY_API_ERROR");
    Marker PAYMENT_RECONCILIATION_QUEUE = MarkerFactory.getMarker("PAYMENT_RECONCILIATION_QUEUE");
    Marker GOOGLE_PLAY_NOTIFICATION_DECODE_ERROR = MarkerFactory.getMarker("GOOGLE_PLAY_NOTIFICATION_DECODE_ERROR");
    Marker GOOGLE_PLAY_NOTIFICATION_VALIDATION_ERROR = MarkerFactory.getMarker("GOOGLE_PLAY_NOTIFICATION_VALIDATION_ERROR");
    Marker GOOGLE_PLAY_NOTIFICATION_ERROR = MarkerFactory.getMarker("GOOGLE_PLAY_NOTIFICATION_ERROR");
    Marker ITUNES_NOTIFICATION_ERROR = MarkerFactory.getMarker("ITUNES_NOTIFICATION_ERROR");
    Marker AMAZON_IAP_NOTIFICATION_ERROR = MarkerFactory.getMarker("AMAZON_IAP_NOTIFICATION_ERROR");
    Marker PAYMENT_RECONCILIATION_FAILURE = MarkerFactory.getMarker("PAYMENT_RECONCILIATION_FAILURE");
    Marker PRE_DEBIT_NOTIFICATION_QUEUE = MarkerFactory.getMarker("PRE_DEBIT_NOTIFICATION_QUEUE");
    Marker PAYMENT_RENEWAL_QUEUE = MarkerFactory.getMarker("PAYMENT_RENEWAL_QUEUE");
    Marker PAYMENT_CHARGING_QUEUE = MarkerFactory.getMarker("PAYMENT_CHARGING_QUEUE");
    Marker RENEWAL_SUBSCRIPTION_QUEUE = MarkerFactory.getMarker("RENEWAL_SUBSCRIPTION_QUEUE");
    Marker USER_DEACTIVATION_SUBSCRIPTION_QUEUE = MarkerFactory.getMarker("USER_DEACTIVATION_SUBSCRIPTION_QUEUE");
    Marker USER_DEACTIVATION_COUPON_MIGRATION_INFO = MarkerFactory.getMarker("USER_DEACTIVATION_COUPON_MIGRATION_INFO");
    Marker USER_DEACTIVATION_TRANSACTION_MIGRATION_INFO = MarkerFactory.getMarker("USER_DEACTIVATION_TRANSACTION_MIGRATION_INFO");
    Marker USER_DEACTIVATION_RECEIPT_MIGRATION_INFO = MarkerFactory.getMarker("USER_DEACTIVATION_RECEIPT_MIGRATION_INFO");
    Marker USER_DEACTIVATION_MIGRATION_ERROR = MarkerFactory.getMarker("USER_DEACTIVATION_MIGRATION_ERROR");

    Marker PAYMENT_CHARGING_CALLBACK_FAILURE = MarkerFactory.getMarker("PAYMENT_CHARGING_CALLBACK_FAILURE");
    Marker PAYMENT_CHARGING_CALLBACK_PENDING = MarkerFactory.getMarker("PAYMENT_CHARGING_CALLBACK_PENDING");
    Marker PAYMENT_VERIFY_USER_PAYMENT_FAILURE = MarkerFactory.getMarker("PAYMENT_VERIFY_USER_PAYMENT_FAILURE");
    Marker PAYU_CHARGING_FAILURE = MarkerFactory.getMarker("PAYU_CHARGING_FAILURE");
    Marker PAYU_RENEWAL_STATUS_ERROR = MarkerFactory.getMarker("PAYU_RENEWAL_STATUS_ERROR");
    Marker PAYU_PRE_DEBIT_NOTIFICATION_SUCCESS= MarkerFactory.getMarker("PAYU_PRE_DEBIT_NOTIFICATION_SUCCESS");
    Marker PAYU_RENEWAL_TIMEOUT_ERROR = MarkerFactory.getMarker("PAYU_RENEWAL_TIMEOUT_ERROR");
    Marker PAYU_CHARGING_CALLBACK_FAILURE = MarkerFactory.getMarker("PAYU_CHARGING_CALLBACK_FAILURE");
    Marker PAYU_CHARGING_STATUS_VERIFICATION = MarkerFactory.getMarker("PAYU_CHARGING_STATUS_VERIFICATION");
    Marker PAYU_PRE_DEBIT_NOTIFICATION_ERROR = MarkerFactory.getMarker("PAYU_PRE_DEBIT_NOTIFICATION_ERROR");
    Marker PAYU_UPI_MANDATE_REVOKE_ERROR = MarkerFactory.getMarker("PAYU_UPI_MANDATE_REVOKE_ERROR");
    Marker PAYU_REFUND_STATUS_VERIFICATION = MarkerFactory.getMarker("PAYU_REFUND_STATUS_VERIFICATION");
    Marker PAYU_CHARGING_STATUS_VERIFICATION_FAILURE = MarkerFactory.getMarker("PAYU_CHARGING_STATUS_VERIFICATION_FAILURE");
    Marker PAYU_API_FAILURE = MarkerFactory.getMarker("PAYU_API_FAILURE");
    Marker ADDTOBILL_API_FAILURE = MarkerFactory.getMarker("ADDTOBILL_API_FAILURE");
    Marker PAYU_UPI_INIT_TXN_FAILURE = MarkerFactory.getMarker("PAYU_UPI_INIT_TXN_FAILURE");

    Marker PHONEPE_CHARGING_FAILURE = MarkerFactory.getMarker("PHONEPE_CHARGING_FAILURE");
    Marker PHONEPE_CHARGING_CALLBACK_FAILURE = MarkerFactory.getMarker("PHONEPE_CHARGING_CALLBACK_FAILURE");
    Marker PHONEPE_CHARGING_STATUS_VERIFICATION = MarkerFactory.getMarker("PHONEPE_CHARGING_STATUS_VERIFICATION");
    Marker PHONEPE_CHARGING_STATUS_VERIFICATION_FAILURE = MarkerFactory.getMarker("PHONEPE_CHARGING_STATUS_VERIFICATION_FAILURE");

    Marker PHONEPE_OTP_SEND_FAILURE = MarkerFactory.getMarker("PHONEPE_OTP_SEND_FAILURE");
    Marker PHONEPE_OTP_VERIFICATION_FAILURE = MarkerFactory.getMarker("PHONEPE_OTP_VERIFICATION_FAILURE");
    Marker PHONEPE_GET_BALANCE_FAILURE = MarkerFactory.getMarker("PHONEPE_GET_BALANCE_FAILURE");
    Marker PHONEPE_UNLINK_FAILURE = MarkerFactory.getMarker("PHONEPE_UNLINK_FAILURE");
    Marker PHONEPE_ADD_MONEY_FAILURE = MarkerFactory.getMarker("PHONEPE_ADD_MONEY_FAILURE");

    Marker PAYTM_CHARGING_STATUS_VERIFICATION = MarkerFactory.getMarker("PAYTM_CHARGING_STATUS_VERIFICATION");

    Marker ITUNES_VERIFICATION_FAILURE = MarkerFactory.getMarker("ITUNES_VERIFICATION_FAILURE");
    Marker GOOGLE_PLAY_VERIFICATION_FAILURE = MarkerFactory.getMarker("GOOGLE_PLAY_VERIFICATION_FAILURE");
    Marker GOOGLE_PLAY_ACKNOWLEDGEMENT_FAILURE = MarkerFactory.getMarker("GOOGLE_PLAY_ACKNOWLEDGEMENT_FAILURE");
    Marker ITUNES_ERROR = MarkerFactory.getMarker("ITUNES_ERROR");
    Marker ITUNES_RENEWAL_ERROR = MarkerFactory.getMarker("ITUNES_RENEWAL_ERROR");
    Marker GOOGLE_PLAY_RENEWAL_ERROR = MarkerFactory.getMarker("GOOGLE_PLAY_RENEWAL_ERROR");

    Marker AMAZON_IAP_VERIFICATION_FAILURE = MarkerFactory.getMarker("AMAZON_IAP_VERIFICATION_FAILURE");

    Marker APB_CHARGING_STATUS_VERIFICATION = MarkerFactory.getMarker("APB_CHARGING_STATUS_VERIFICATION");
    Marker APB_CHARGING_CALLBACK_FAILURE = MarkerFactory.getMarker("APB_CHARGING_CALLBACK_FAILURE");

    Marker POINT_PURCHASE_SESSION_INIT_FAILURE = MarkerFactory.getMarker("POINT_PURCHASE_SESSION_INIT_FAILURE");
    Marker NOT_SUPPORTED_SERVICE = MarkerFactory.getMarker("NOT_SUPPORTED_SERVICE");

    Marker PAYMENT_RENEWAL_ERROR = MarkerFactory.getMarker("PAYMENT_RENEWAL_ERROR");
    Marker SE_PAYMENT_RENEWAL_ERROR = MarkerFactory.getMarker("SE_PAYMENT_RENEWAL_ERROR");

    Marker PAYMENT_REFUND_ERROR = MarkerFactory.getMarker("PAYMENT_REFUND_ERROR");

    Marker CLIENT_CALLBACK_INFO = MarkerFactory.getMarker("CLIENT_CALLBACK_INFO");

    Marker SAVED_OPTIONS_TIMED_OUT = MarkerFactory.getMarker("SAVED_OPTIONS_TIMED_OUT");
    Marker LINK_WALLET_ERROR = MarkerFactory.getMarker("LINK_WALLET_ERROR");
    Marker SAVED_CARDS_ERROR = MarkerFactory.getMarker("SAVED_CARDS_ERROR");

    Marker AMAZON_SERVICE_ERROR = MarkerFactory.getMarker("AMAZON_SERVICE_ERROR");

    Marker SDK_CLIENT_ERROR = MarkerFactory.getMarker("SDK_CLIENT_ERROR");
    Marker APB_PAYTM_OTP_SEND_FAILURE=MarkerFactory.getMarker("APB_PAYTM_OTP_SEND_FAILURE");
    Marker APB_PAYTM_OTP_VALIDATE_FAILURE=MarkerFactory.getMarker("APB_PAYTM_OTP_VALIDATE_FAILURE");
    Marker APB_PAYTM_ADD_MONEY_FAILURE=MarkerFactory.getMarker("APB_PAYTM_ADD_MONEY_FAILURE");
    Marker APB_PAYTM_CHARGE_FAILURE=MarkerFactory.getMarker("APB_PAYTM_CHARGE_FAILURE");
    Marker APB_PAYTM_GET_BALANCE_FAILURE=MarkerFactory.getMarker("APB_PAYTM_GET_BALANCE_FAILURE");
    Marker APB_PAYTM_CHARGING_STATUS_VERIFICATION=MarkerFactory.getMarker("APB_PAYTM_CHARGING_STATUS_VERIFICATION");
    Marker ADDTOBILL_CHARGING_STATUS_VERIFICATION=MarkerFactory.getMarker("ADDTOBILL_CHARGING_STATUS_VERIFICATION");
    Marker CALLBACK_PAYLOAD_PARSING_FAILURE = MarkerFactory.getMarker("CALLBACK_PAYLOAD_PARSING_FAILURE");

    Marker PAYMENT_OPTIONS_FAILURE = MarkerFactory.getMarker("PAYMENT_OPTIONS_FAILURE");
    Marker VAS_ERROR = MarkerFactory.getMarker("VAS_ERROR");
    Marker PAYMENT_ELIGIBILITY_INFO = MarkerFactory.getMarker("PAYMENT_ELIGIBILITY_INFO");

}