package in.wynk.payment.core.constant;

import in.wynk.common.constant.BaseConstants;

public interface PaymentConstants extends BaseConstants {
    String SKU_ID = "skuId";
    String PAYU = "PAYU";
    String TXN_ID = "tid";
    String ERROR = "error";
    String VERSION_2 = "V2";
    String SUBSID = "subsId";
    String STATUS = "status";
    String FAILED = "failed";
    String QUEUED = "queued";
    String PROD_ENV = "PROD";
    int MERCHANT_CODE = 5815;
    String ITUNES = "ITUNES";
    String MERCHANT_ID = "id";
    String FAILURE = "failure";
    String AUTO_REFUND = "autoRefund";
    String RENEWAL = "renewal";
    String REQUEST = "request";
    String PENDING = "pending";
    String SUCCESS = "success";
    String MESSAGE = "message";
    String PIPE_SEPARATOR = "|";
    String SOURCE_MODE = "mode";
    String BANK_CODE = "bankCode";
    String SANDBOX_ENV = "Sandbox";
    String MERCHANT_TOKEN = "token";
    String SE_BILLING = "SE_BILLING";
    String AMAZON_IAP = "AMAZON_IAP";
    String GOOGLE_IAP = "GOOGLE_IAP";
    String SUBTITLE_TEXT = "subtitle";
    String BUTTON_TEXT = "buttonText";
    String MERCHANT_SECRET = "secret";
    String APB_GATEWAY = "APB_GATEWAY";
    String DEFAULT_PN = "Wynk Limited";
    String ADD_TO_BILL = "ADD_TO_BILL";
    String HTML_TYPE = "HTML_TYPE";
    String DEFAULT_COUNTRY_CODE = "IN";
    String APP_NAME = "APP_NAME";
    String BASE_USER_EMAIL = "@wynk.in";
    String BILLING = "BILLING";
    String APP_PACKAGE = "package_name";
    String PAYMENT_CODE = "paymentCode";
    String PAYMENT_MODE = "paymentMode";
    String BUTTON_ARROW = "buttonArrow";
    String USER_WINBACK = "user_winback";
    String MERCHANT_CLIENT_ID = "clientId";
    String CLIENT_ALIAS = "client";
    String PAYMENT_METHOD = "paymentMethod";
    String TDR ="tdr";
    String PAYU_CHARGE ="PayU_charge";
    String PAYU_CALLBACK ="PayU_callback";
    String PAYU_PAYMENT_STATUS ="PayU_payment_status";
    String APS_PAYMENT_STATUS ="aps_payment_status";
    String PAYU_VERIFY ="PayU_verify";
    String SHOULD_WINBACK = "shouldWinBack";
    String MIGRATED_TXN_ID = "transactionid";
    String PAYMENT_API_CLIENT = "paymentApi";
    String PAYMENT_GATEWAY = "paymentGateway";
    String REQUEST_PAYLOAD = "requestPayload";
    String ATTEMPT_SEQUENCE = "attemptSequence";
    String WINBACK_CAMPAIGN = "winback_campaign";

    String PHONEPE_AUTO_DEBIT = "PHONEPE_AUTO_DEBIT";
    String PAY_OPTION_DEEPLINK = "pay_option_deeplink";
    String PAYMENT_DETAILS_KEY = "PAYMENT_DETAILS_KEY:";
    String MERCHANT_TRANSACTION = "merchantTransaction";
    String PAYMENT_PAGE_PLACE_HOLDER = "${payment.%c.%p.page}";
    String ORIGINAL_TRANSACTION_ID = "ORIGINAL_TRANSACTION_ID";
    String PAYMENT_DROPOUT_DELAY_KEY = "transactionTrackerDelaySec";
    String PAYMENT_ENTITY_BASE_PACKAGE = "in.wynk.payment.core.dao";
    String PAYMENT_CLIENT_PLACE_HOLDER = "payment.merchant.%p.%c.%f";
    String PAYMENT_ERROR_UPSERT_RETRY_KEY = "paymentErrorUpsertRetry";
    String PAYMENT_CLIENT_CALLBACK_RETRY = "paymentClientCallbackRetry";
    String MERCHANT_TRANSACTION_UPSERT_RETRY_KEY = "merchantTransactionUpsertRetry";
    String PAYMENT_CLIENT_AUTHORIZATION = "authentication.details.getApiServices().contains(\"payment\")";

    String WYNK_LIMITED = "Wynk Limited";
    String CHANNEL_ID = "channel-id";
    String AUTH_TYPE_WEB_UNAUTH = "WEB_UNAUTH";
    String CONTENT_TYPE = "Content-Type";
    String APPLICATION_JSON = "application/json";
    String ORDER_ID = "orderId";

    String AIRTEL_PAY_STACK = "aps";
    String AIRTEL_PAY_STACK_CHARGE = "aps_charge";
    String AIRTEL_PAY_STACK_VERIFY = "aps_verify";
    String AIRTEL_PAY_STACK_RENEW = "aps_renew";
    String APS = "APS";
    String CHARGE = "_charge";
    String VERIFY = "_verify";
    String RENEW = "_renew";
    String CALLBACK="_callback";
    String PAYMENT_STATUS="_payment_status";
}