package in.wynk.payment.core.constant;

public class PaymentConstants {
  public static final String PAYU_BSYS_PARAM = "bsys";
  public static final String NETBANKING_MODE = "netbanking";
  public static final String SID_KEY = "{sid}";
  public static final String PIPE_SEPARATOR = "|";
  public static final String COLON = ":";
  public static final String BASE_USER_EMAIL = "@wynk.in";
  public static final String PAYU_REQUEST_TYPE = "rt";
  public static final String PAYU_CHARGING_INFO = "info";
  public static final String PAYU_MERCHANT_KEY = "key";
  public static final String PAYU_COMMAND = "command";
  public static final String PAYU_HASH = "hash";
  public static final String PAYU_VARIABLE1 = "var1";
  public static final String PAYU_REQUEST_TRANSACTION_ID = "txnid";
  public static final String PAYU_TRANSACTION_AMOUNT = "amount";
  public static final String PAYU_PRODUCT_INFO = "productinfo";
  public static final String PAYU_CUSTOMER_FIRSTNAME = "firstname";
  public static final String PAYU_CUSTOMER_EMAIL = "email";
  public static final String PAYU_CUSTOMER_MSISDN = "phone";
  public static final String PAYU_ENFORCE_PAYMENT = "enforce_payment";
  public static final String PAYU_SUCCESS_URL = "surl";
  public static final String PAYU_FAILURE_URL = "furl";
  public static final String PAYU_USER_CREDENTIALS = "user_credentials";
  public static final String PAYU_ENFORCE_PAY_METHOD = "enforce_paymethod";
  public static final String PAYU_UDF1_PARAMETER = "udf1";
  public static final String IS_FALLBACK_ATTEMPT = "isFallbackAttempt";
  public static final String ERROR = "error";
  public static final String PAYU_REDIRECT_MESSAGE = "Redirecting to PayU ";
  public static final String CARD_DETAILS = "CardDetails";
  public static final String PAYU_PG = "pg";
  public static final String PAYU_SI_KEY = "si";
  public static final String SUBSID = "subsId";
  public static final String PAYU_CARD_NUMBER = "card_no";
  public static final String SUCCESS = "success";
  public static final String FAILURE = "failure";
  public static final String STATUS = "status";
  public static final String MESSAGE = "message";
  public static final String INPROGRESS = "inprogress";
  public static final String PAYU_STATUS_NOT_FOUND = "Not Found";
  public static final String PENDING = "pending";
  public static final String PAYU_RESPONSE_AUTH_PAYUID = "authpayuid";
  public static final String PAYU_CARD_TOKEN = "card_token";
  public static final String TRANSACTION_FAILED = "TXN Failed";
  public static final String TRANSACTION_ID = "transactionid";
  public static final String SESSION_ID = "sessionId";
  public static final String PAYU_ERROR_MESSAGE = "Error";
  public static final String PAYU_RESPONSE_ERROR_MESSAGE = "error_Message";
  public static final String PAYU_STATUS_CAPTURED = "captured";
  public static final String PAYU_SI_STATUS_FAILURE = "failed";
  public static final String X_VERIFY = "x-verify";
  public static final String CONTENT_TYPE = "content-type";
  public static final String X_REDIRECT_URL = "x-redirect-url";
  public static final String X_REDIRECT_MODE = "x-redirect-mode";
  public static final String BSYS = "bsys";
  public static final String REQUEST = "request";


}
