package in.wynk.payment.constant;

public enum FlowType {
    INTENT, INAPP, COLLECT, SEAMLESS, NON_SEAMLESS, COLLECT_IN_APP, NON_SEAMLESS_REDIRECT_FLOW,
    OTP_LESS, FORM_BASED, UPI, CARD, NET_BANKING, WALLET, KEY_VALUE, HTML;
}
